// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README to configure your Firebase project.
// This configuration is for a sample project and should be replaced with your
// own project's configuration from the Firebase console.
export const firebaseConfig = {
  "projectId": "studio-6387478031-6620a",
  "appId": "1:204056142325:web:ae9916313e99ac069240bc",
  "apiKey": "AIzaSyC9vxdcs-zLsMCYmuQykJ0oobWHBKM5XrE",
  "authDomain": "studio-6387478031-6620a.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "204056142325"
};
