// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README to configure your Firebase project.
// This configuration is for a sample project and should be replaced with your
// own project's configuration from the Firebase console.
export const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-project-id.firebaseapp.com",
  projectId: "your-project-id",
  storageBucket: "your-project-id.appspot.com",
  messagingSenderId: "your-sender-id",
  appId: "your-app-id",
};
